on:
  schedule:
  - cron: '0 13-21/2 * * 1-5'
jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
           go-package: ./...
